import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '../../components/NavBar'
import { useRouter } from 'next/router'
import CommonTag from '@/components/tag/CommonTag'
import TagList from '@/components/tag/TagList'
import { tutorWithUserInfo } from '../api/tutor'

type Props = {}

const TutorPage = (props: Props) => {
    const [tutorData, setTutorData] = React.useState<tutorWithUserInfo>()
    const [isLoading, setLoading] = React.useState(true)
    const router = useRouter()
    const { tutorId } = router.query

    useEffect(() => {
        const fetchTutor = async () => {
            await fetch('../../api/tutor/'+tutorId, {method: 'GET'})
            .then((resp) => resp.json())
            .then((json) => {
            // Update data state
            setTutorData(json)
            
            // Stop loading
            setLoading(false)
            })
        }
        fetchTutor()
        console.log(tutorData)
    })

    if( isLoading ) {
        return <><h1>Loading...</h1></>
    }

    if( tutorData == undefined ) {
        return <><h1>"Error Loading Page.</h1></>
    }
    else {
        return (
            <>
                <Head>
                    <title>Tutor Page</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <NavBar />
                    <div className='p-4 flex flex-col items-center'>
                        <div className='flex flex-col lg:flex-row gap-8 mb-8'>
                            <div className='bg-gray-400 w-40 h-40 rounded-full' />
                            <div>
                                <span className='text-lg font-bold'>{tutorData.first_name + " " + tutorData.last_name}</span>
                                <p>{tutorData.about_me}</p>
                                <TagList tags={tutorData.subjects.map((x) => {
                                    return x.name
                                })}
                                    className='mt-2'
                                />
                                <span>Tutor Id = {tutorId}</span>
                            </div>
                        </div>
                        <div className='w-full h-80 bg-gray-400 flex items-center justify-center'>
                            <span>Calendar</span>
                        </div>
                    </div>
                </main>
            </>
        )
    }
}

export default TutorPage