import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '../../components/NavBar'
import { useRouter } from 'next/router'
import CommonTag from '@/components/tag/CommonTag'
import TagList from '@/components/tag/TagList'
import { tutor, user, subject, tutors_subjects } from '@prisma/client'

type Props = {}

type TutorWithSubjects = tutor & {
    subjects: tutors_subjects[];
};

const TutorPage = (props: Props) => {
    const [tutorData, setTutorData] = React.useState<tutor>()
    const [tutorUserData, setTutorUserData] = React.useState<user>()
    const [tutorSubjectData, setTutorSubjectData] = React.useState<subject[]>()
    const [isLoading, setLoading] = React.useState(true)
    const router = useRouter()
    const { tutorId } = router.query

    const fetchTutorData = async () => {
        await fetch('../../api/tutor/'+tutorId, {method: 'GET'})
        .then((resp) => resp.json())
        .then((json) => {
            let result = json as TutorWithSubjects

            // Fetch user data
            fetchTutorUserData(result)

            // Fetch subject data
            fetchTutorSubjectData(result)

            // Update data state
            setTutorData(result)
        })
    }

    const fetchTutorUserData = async (tut: tutor) => {
        // Get tutor's user data
        await fetch('../../api/user/' + tut.fk_userID, {method: 'GET'})
        .then((resp) => resp.json())
        .then((json) => {
            // read json as user, return it
            let result = json as user

            // Update user data state
            setTutorUserData(result)
        })
        .catch((error) => {
            return
        })
    }

    const fetchTutorSubjectData = async (tut: TutorWithSubjects) => {
        // Get subjects lists
        let subjects: subject[] = []
        await Promise.all(tut.subjects.map(async (tut_sub:tutors_subjects) => {
            await fetch('../../api/subject/' + tut_sub.fk_subjectID, {method: 'GET'})
            .then((resp) => resp.json())
            .then((json) => {
                // read json as subject, return it
                let result = json as subject
                subjects.push(result)
            })
        }))

        // Update subject state
        setTutorSubjectData(subjects)
            
        // Stop loading
        setLoading(false)
    }
    
    useEffect(() => {
        if(tutorId)
            fetchTutorData()
    }, [tutorId])

    if( isLoading ) {
        return <><h1>Loading...</h1></>
    }

    if( tutorData == undefined || tutorUserData == undefined || tutorSubjectData == undefined ) {
        return <><h1>"Error Loading Page.</h1></>
    }
    else {
        return (
            <>
                <Head>
                    <title>Tutor Page</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <NavBar />
                    <div className='p-4 flex flex-col items-center'>
                        <div className='flex flex-col lg:flex-row gap-8 mb-8'>
                            <img src={tutorData.profile_picture ? tutorData.profile_picture : ''} alt='Image Not Found' className='bg-gray-400 w-40 h-40 rounded-full' onError={({currentTarget}) => {
                                // Replace with empty profile picture if src image dne
                                currentTarget.onerror = null
                                currentTarget.src='/emptyprofile.svg'
                            }} />
                            <div>
                                <span className='text-lg font-bold'>{tutorUserData.first_name + " " + tutorUserData.last_name}</span>
                                <p>{tutorData.about_me}</p>
                                <TagList tags={tutorSubjectData}
                                    className='mt-2'
                                />
                                <span>Tutor Id = {tutorId}</span>
                            </div>
                        </div>
                        <div className='w-full h-80 bg-gray-400 flex items-center justify-center'>
                            <span>Calendar</span>
                        </div>
                    </div>
                </main>
            </>
        )
    }
}

export default TutorPage