import React from 'react'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import { useRouter } from 'next/router'
import CommonInput from '@/components/CommonInput'
import { IoCamera, IoSettingsOutline } from 'react-icons/io5'

type Props = {}

const AccountPage = (props: Props) => {
    const router = useRouter()
    const { tutorId } = router.query

    return (
        <>
            <Head>
                <title>My Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NavBar />
                <div className='p-4 flex flex-col items-center'>
                    <div className='flex flex-col gap-8 mb-8'>
                        <div className='flex items-center gap-4'>
                            <button className='relative h-fit w-20'>
                                <div className='bg-gray-400 w-20 h-20 rounded-full' />
                                {/* <div className='absolute bottom-1 right-1 bg-secondary rounded-full p-2'>
                                    <IoCamera className='' size='1.25rem' />
                                </div> */}
                            </button>
                            <div className='flex flex-col'>
                                <span className='text-primary text-lg'>Micah Katz</span>
                                <button>
                                    <span className='text-link font-bold hover:text-primary text-sm'>Change profile photo</span>
                                </button>
                            </div>
                            <div className='flex flex-1 justify-end'>
                                <button>
                                    <IoSettingsOutline className='' size='1.5rem' />
                                </button>
                            </div>
                        </div>
                        <div className='flex flex-col'>
                            <div className='flex gap-4 md:w-auto flex-col md:flex-row'>
                                <CommonInput
                                    placeholder='First Name'
                                />
                                <CommonInput
                                    placeholder='Last Name'
                                />
                            </div>
                            <CommonInput
                                innerClass='h-40'
                                placeholder='About Me'
                                type='TextArea'
                            />
                            <button className='bg-primary w-fit px-4 py-1 mt-2 rounded-lg text-inverted'>
                                Save Profile
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default AccountPage