import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '../components/NavBar'
import { useRouter } from 'next/router'
import CommonTag from '@/components/tag/CommonTag'
import TagList from '@/components/tag/TagList'
import CommonInput from '@/components/CommonInput'
import { IoCamera } from 'react-icons/io5'

type Props = {}

const AccountPage = (props: Props) => {
    const router = useRouter()
    const { tutorId } = router.query

    return (
        <>
            <Head>
                <title>My Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NavBar />
                <div className='p-4 flex flex-col items-center'>
                    <div className='flex flex-col lg:flex-row gap-8 mb-8'>
                        <button className='relative h-fit'>
                            <div className='bg-gray-400 w-40 h-40 rounded-full' />
                            <div className='absolute bottom-1 right-1 bg-secondary rounded-full p-2'>
                                <IoCamera className='' size='2rem' />
                            </div>
                        </button>
                        <div className='flex flex-col'>
                            <div className='flex gap-4'>
                                <CommonInput
                                    placeholder='First Name'
                                />
                                <CommonInput
                                    placeholder='Last Name'
                                />
                            </div>
                            <CommonInput
                                innerClass='h-40'
                                placeholder='About Me'
                                type='TextArea'
                            />
                            <button className='bg-primary w-fit px-2 py-1 rounded-lg'>
                                Save Profile
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default AccountPage