import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '../components/NavBar'
import { useRouter } from 'next/router'
import CommonTag from '@/components/tag/CommonTag'
import TagList from '@/components/tag/TagList'

type Props = {}

const AccountPage = (props: Props) => {
    const router = useRouter()
    const { tutorId } = router.query

    return (
        <>
            <Head>
                <title>Tutor Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NavBar />
                <div className='p-4 flex flex-col items-center'>
                    <div className='flex flex-col lg:flex-row gap-8 mb-8'>
                        <div className='bg-gray-400 w-40 h-40 rounded-full' />
                        <div>
                            <span className='text-lg font-bold'>John Doe</span>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default AccountPage