import React from 'react'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import AppointmentCard from '../components/AppointmentCard'
import Link from 'next/link'

type Props = {}

const Appointments = (props) => {
    return (
        <>
            <Head>
                <title>My Appointments</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NavBar />
                <h1 className='text-center text-5xl mb-6 font-bold'>My Appointments</h1>
                <div className='flex flex-col items-center'>
                    <div className='gird grid-cols-1 justify-center w-full max-w-[66%] lg:max-w-[50%] xl:max-w-[40%]'>
                        <div className='w-full'>
                            <h2 className='text-center text-4xl'>Next:</h2>
                            <AppointmentCard className='w-full'
                                startDT={new Date('3:00 PM 3/27/2023')}
                                endDT={new Date('4:00 PM 3/27/2023')}
                            />
                        </div>
                        <div className='w-full'>
                            <h2 className='text-center text-4xl'>Upcoming:</h2>
                            <AppointmentCard className='w-full'
                                startDT={new Date('3:00 PM 3/27/2023')}
                                endDT={new Date('4:00 PM 3/27/2023')}
                            />
                            <AppointmentCard className='w-full'
                                startDT={new Date('3:00 PM 3/27/2023')}
                                endDT={new Date('4:00 PM 3/27/2023')}
                            />
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Appointments