import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '../components/NavBar'
import ActionPanel from '../components/ActionPanel'
import TutorFeed from '../components/TutorFeed'
import TutorCard from '@/components/TutorCard'
import SearchBar from '@/components/SearchBar'
import { UserContext } from '@/context/userContext'
import { subject } from '@prisma/client'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [nameFilter, setNameFilter] = React.useState<string>("")
  const [subjectFilter, setSubjectFilter] = React.useState<string>("")
  const [dayFilter, setDayFilter] = React.useState<Date>()
  const [hourFilter, setHourFilter] = React.useState<Date>()
  const [isLoading, setLoading] = React.useState<boolean>(true)
  const userContext = React.useContext(UserContext);

  React.useEffect(() => {
    if(userContext?.currUser)
      setLoading(false)
    else
      location.href = '/login'
  }, [])

  if(isLoading) {
    return <></>
  }
  else {
    return (
      <>
        <Head>
          <title>Tutor.io</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <NavBar />
          <ActionPanel />
          <div className='p-4 flex flex-col items-center'>
            <SearchBar setName={setNameFilter} subject={subjectFilter} setSubject={setSubjectFilter} day={dayFilter} setDay={setDayFilter} hour={hourFilter} setHour={setHourFilter}/>
            <TutorFeed filterName={nameFilter} filterSubject={subjectFilter} filterDay={dayFilter} filterHour={hourFilter}/>
          </div>
        </main>
      </>
    )
  }
}
