import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '../components/NavBar'
import { useRouter } from 'next/router'
import CommonTag from '@/components/tag/CommonTag'
import TagList from '@/components/tag/TagList'
import CommonInput from '@/components/CommonInput'
import { IoCamera } from 'react-icons/io5'

type Props = {}

const LoginPage = (props: Props) => {
  const router = useRouter()
  const { tutorId } = router.query

  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <div className='p-4'>
          <div className='max-w-[40rem] m-auto'>
            <h1 className='font-bold text-2xl mb-2'>Login</h1>
            <CommonInput
              placeholder='Email'
              type='email'
            />
            <CommonInput
              placeholder='Password'
              type='password'
            />
            {/* <CommonInput
              innerClass='h-40'
              placeholder='About Me'
              inputType='TextArea'
            /> */}
            <button className='bg-primary w-fit px-4 py-1 mt-2 text-inverted rounded-lg'>
              Login
            </button>
          </div>
        </div>
      </main>
    </>
  )
}

export default LoginPage